CREATE TABLE `rs_listed_company_detail` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `code` int(11) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `ename` varchar(255) DEFAULT NULL,
  `market` varchar(255) DEFAULT NULL,
  `ldate` varchar(255) DEFAULT NULL,
  `sprice` varchar(255) DEFAULT NULL,
  `principal` varchar(255) DEFAULT NULL,
  `rdate` varchar(255) DEFAULT NULL,
  `rprice` varchar(255) DEFAULT NULL,
  `instype` varchar(255) DEFAULT NULL,
  `organ` varchar(255) DEFAULT NULL,
  `secre` varchar(255) DEFAULT NULL,
  `new_tablecol` varchar(255) DEFAULT NULL,
  `phone` varchar(255) DEFAULT NULL,
  `sphone` varchar(255) DEFAULT NULL,
  `fax` varchar(255) DEFAULT NULL,
  `sfax` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `semail` varchar(255) DEFAULT NULL,
  `site` varchar(255) DEFAULT NULL,
  `post` varchar(255) DEFAULT NULL,
  `infosite` varchar(255) DEFAULT NULL,
  `oname` varchar(255) DEFAULT NULL,
  `addr` varchar(255) DEFAULT NULL,
  `oaddr` varchar(255) DEFAULT NULL,
  `desc` varchar(2000) DEFAULT NULL,
  `bscope` varchar(255) DEFAULT NULL,
  `idea` varchar(255) DEFAULT NULL,
  `printype` varchar(255) DEFAULT NULL,
  `referrer` varchar(255) DEFAULT NULL,
  `putype` varchar(255) DEFAULT NULL,
  `pe` varchar(255) DEFAULT NULL,
  `firgu` varchar(255) DEFAULT NULL,
  `lastgu` varchar(255) DEFAULT NULL,
  `realgu` varchar(255) DEFAULT NULL,
  `planm` varchar(255) DEFAULT NULL,
  `realm` varchar(255) DEFAULT NULL,
  `pubfee` varchar(255) DEFAULT NULL,
  `collect` varchar(255) DEFAULT NULL,
  `signfee` varchar(255) DEFAULT NULL,
  `pdate` varchar(255) DEFAULT NULL,
  `update_date` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `code` (`code`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4